INSERT INTO USER (user_id, PASSWORD, FIRST_NAME, LAST_NAME, username, ENABLED, LAST_PASSWORD_RESET_DATE) VALUES (1, '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', 'a@a.com', 1, '2016-01-01 00:00:00');
INSERT INTO USER (user_id, PASSWORD, FIRST_NAME, LAST_NAME, username, ENABLED, LAST_PASSWORD_RESET_DATE) VALUES (2, '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'u@u.com', 1, '2016-01-01 00:00:00');
INSERT INTO USER (user_id, PASSWORD, FIRST_NAME, LAST_NAME, username, ENABLED, LAST_PASSWORD_RESET_DATE) VALUES (3, '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'd@d.com', 0, '2016-01-01 00:00:00');

INSERT INTO ROLE (ROLE_ID, role) VALUES (1, 'ROLE_USER');
INSERT INTO ROLE (ROLE_ID, role) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (3, 1);
